# Generated by Django 4.2 on 2023-04-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('N_huespedes', models.PositiveBigIntegerField()),
                ('tipoAbitacion', models.CharField(max_length=30)),
                ('precioTotal', models.CharField(max_length=100)),
                ('estadoReserva', models.CharField(max_length=60)),
            ],
        ),
    ]
